language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - /tmp/cache/unicode_conformance
    - /tmp/beanstalkd-1.10

services:
  - memcached
  - redis
  - rabbitmq

addons:
  postgresql: "9.4"

bundler_args: --without test --jobs 3 --retry 3
#FIXME: Remove bundler uninstall on Travis when https://github.com/bundler/bundler/issues/4493 is fixed.
before_install:
  - rvm @global do gem uninstall bundler --all --ignore-dependencies --executables
  - rvm @global do gem install bundler -v '1.11.2'
  - bundle --version
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "[ -f /tmp/beanstalkd-1.10/Makefile ] || (curl -L https://github.com/kr/beanstalkd/archive/v1.10.tar.gz | tar xz -C /tmp)"
  - "pushd /tmp/beanstalkd-1.10 && make && (./beanstalkd &); popd"

before_script:
  - bundle update

script: 'ci/travis.rb'

env:
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=ac"
    - "GEM=ac FAYE=1"
    - "GEM=am,amo,as,av,aj"
    - "GEM=as PRESERVE_TIMEZONES=1"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
    - "GEM=aj:integration"
    - "GEM=guides"
  global:
  - secure: ctwuhhY76OFhI/lmK054lL4Tzmney3l3gpnCkzlZ8idMAbeKAPOGdJxx7QUVQi3dY3N9lg+iAhKGNk+/J/ze7SG0gjGFsjAjqzIZonirwkfNIZrTgWmkclE4IbqAU9rG7kvsobzlMNNpS7sfmoT4vabvsJyCMObuEfBnaVZE0DA=
  - secure: bcEdBn7qw0KpbPIzTMN0fL6CNmpUZHGm3QJfThRzDm9S4X1Y5Yo063TXtb8nvy4P7019MPGezNd6Xw3kslB1D3g6R9nnEUrB0jd94VdKqw+HJzHkaT/hdGoB5ODVgIfrUcfAuElwT+7jd1Fx5JjtYbEgQjlVOyw0mk4SiV88IJQ=

rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head

matrix:
  include:
    # Latest compiled version in http://rubies.travis-ci.org
    - rvm: 2.3.1
      env:
        - "GEM=ar:mysql2"
      addons:
        mariadb: 10.0
    - rvm: jruby-9.0.5.0
      jdk: oraclejdk8
      env:
        - "JRUBY_OPTS='--dev -J-Xmx1024M'"
        - "GEM='ap'"
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
  fast_finish: true

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "YA1alef1ESHWGFNVwvmVGCkMe4cUy4j+UcNvMUESraceiAfVyRMAovlQBGs6\n9kBRm7DHYBUXYC2ABQoJbQRLDr/1B5JPf/M8+Qd7BKu8tcDC03U01SMHFLpO\naOs/HLXcDxtnnpL07tGVsm0zhMc5N8tq4/L3SHxK7Vi+TacwQzI="
